name: PacketMines
version: '${project.version}'
main: me.frxq15.packetmines.PacketMines
load: POSTWORLD
depend:
  - packetevents

commands:
  amine:
    description: Main command for PacketMines plugin
    usage: /<command> <subcommand>
    aliases: [adminmine, packetmine]